training:
  batch_size: 4096
  learning_rate: 0.001
  epochs: 15

paths:
  tokenizer: "model/tokenizer.joblib"
  subsampled: "model/subsampled.joblib"
  dataset: "data/trwiki.parquet"

model:
  k_neg: 5
  emb_dim: 512
  vocab_size: 500000